///|
pub extend Regex with Debug::{to_repr}

///|
pub extend Regex with Eq::{not_equal, equal}

///|
pub extend Regex with ToJson::{to_json}

///|
pub extend Regex with Show::{to_string, output}

///|
pub extend RegexDesc with Debug::{to_repr}

///|
pub extend RegexDesc with Eq::{not_equal, equal}

///|
pub extend RegexDesc with ToJson::{to_json}

///|
pub extend RegexDesc with Show::{to_string, output}

///|
pub extend RegexClass with Debug::{to_repr}

///|
pub extend RegexClass with Eq::{not_equal, equal}

///|
pub extend RegexClass with ToJson::{to_json}

///|
pub extend RegexClass with Show::{to_string, output}

///|
pub extend Encoding with Debug::{to_repr}

///|
pub extend Encoding with Eq::{not_equal, equal}

///|
pub extend Encoding with ToJson::{to_json}

///|
pub extend Encoding with Show::{to_string, output}
